# Heavy Supplier, Inventory & Warehouse Analytics

## Task A1 — Data Profiling & Structure Analysis

### Objective
Understand the structure, size, data types, missing values,
duplicates, and relationships across all available datasets
before performing data cleaning and analysis.

In [1]:
#import libraries
import pandas as pd #working woth datasets
import numpy as np #numerical operations
import os #working with folders/files
import glob #finding multiple csv files

In [2]:
os.listdir('/content')

['.config',
 '01_data_profiling.ipynb',
 'HeavySuppliersWarehouseDatasets.zip',
 'sample_data']

In [3]:
import zipfile
zip_path='/content/HeavySuppliersWarehouseDatasets.zip'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
  zip_ref.extractall('/content/heavy_supplier_data')

In [4]:
os.listdir('/content/heavy_supplier_data/HeavySuppliersWarehouseDatasets')

['purchase_orders_header.csv',
 'payments.csv',
 'customers.csv',
 'sales_orders_lines.csv',
 'stock_ledger.csv',
 'branches.csv',
 'purchase_orders_lines.csv',
 'products.csv',
 'suppliers.csv',
 'inventory_master.csv',
 'sales_orders_header.csv',
 'invoices.csv']

In [5]:
DATA_PATH='/content/heavy_supplier_data/HeavySuppliersWarehouseDatasets/'

In [6]:
os.listdir(DATA_PATH)

['purchase_orders_header.csv',
 'payments.csv',
 'customers.csv',
 'sales_orders_lines.csv',
 'stock_ledger.csv',
 'branches.csv',
 'purchase_orders_lines.csv',
 'products.csv',
 'suppliers.csv',
 'inventory_master.csv',
 'sales_orders_header.csv',
 'invoices.csv']

In [7]:
files=glob.glob(os.path.join(DATA_PATH, '*.csv'))
print('csv files found:', len(files))

for file in files:
  print(os.path.basename(file))

csv files found: 12
purchase_orders_header.csv
payments.csv
customers.csv
sales_orders_lines.csv
stock_ledger.csv
branches.csv
purchase_orders_lines.csv
products.csv
suppliers.csv
inventory_master.csv
sales_orders_header.csv
invoices.csv

In [8]:
#load datasets

datasets={}

for file in files:
  name=os.path.basename(file).replace('.csv', '')
  datasets[name]=pd.read_csv(file)

print('Datasets Loaded:', len(datasets))

Datasets Loaded: 12

In [ ]:
#create the datasets summary

dataset_summary=[]

for name, df in datasets.items():
  dataset_summary.append({
      'Datasets': name,
      'Rows': df.shape[0],
      'Columns': df.shape[1],
      'Missing_Values': df.isnull().sum().sum(),
      'Duplicate_Rows': df.duplicated().sum()
  })
dataset_summary=pd.DataFrame(dataset_summary)
dataset_summary

                  Datasets    Rows  Columns  Missing_Values  Duplicate_Rows
0    purchase_orders_lines  155495        9               0               0
1                customers     500       15               0               0
2   purchase_orders_header   24000       10            2370               0
3       sales_orders_lines  130402        9               0               0
4         inventory_master     180        8               0               0
5                 branches       6       13               0               0
6                suppliers       8       12               0               0
7                 payments   19257        5               0               0
8             stock_ledger  237230        9               0               0
9                 products      30       23               0               0
10                invoices   18033       10               0               0
11     sales_orders_header   20000       11               0               0

In [ ]:
#find the structure of every dataset
for name, df in datasets.items():
  print('\n' + '=' * 60)
  print(f'{name}')
  print('=' * 60)
  print('Shape:', df.shape)
  print('Columns')
  print(df.columns.tolist())

============================================================
purchase_orders_lines
============================================================
Shape: (155495, 9)
Columns
['po_id', 'line_number', 'product_id', 'quantity', 'unit_cost', 'gst_rate', 'line_total', 'gst_amount', 'line_grand_total']

============================================================
customers
============================================================
Shape: (500, 15)
Columns
['customer_id', 'customer_type', 'industry_segment', 'city', 'state', 'pincode', 'region', 'branch_id', 'credit_limit', 'current_balance', 'payment_terms', 'customer_since', 'last_purchase_date', 'total_purchase_value', 'customer_rating']

============================================================
purchase_orders_header
============================================================
Shape: (24000, 10)
Columns
['po_id', 'supplier_id', 'branch_id', 'order_date', 'expected_delivery_date', 'received_date', 'po_status', 'total_cost', 'total_gst_amount', 'grand_total']

============================================================
sales_orders_lines
============================================================
Shape: (130402, 9)
Columns
['so_id', 'line_number', 'product_id', 'quantity', 'unit_price', 'gst_rate', 'line_total', 'gst_amount', 'line_grand_total']

============================================================
inventory_master
============================================================
Shape: (180, 8)
Columns
['product_id', 'branch_id', 'opening_stock', 'reorder_level', 'safety_stock', 'max_stock', 'current_stock', 'warehouse_bin']

============================================================
branches
============================================================
Shape: (6, 13)
Columns
['branch_id', 'branch_name', 'city', 'state', 'region', 'warehouse_type', 'warehouse_capacity', 'service_center_available', 'manager_id', 'total_employees', 'avg_monthly_revenue', 'monthly_operational_cost', 'market_demand_index']

============================================================
suppliers
============================================================
Shape: (8, 12)
Columns
['supplier_id', 'supplier_name', 'supplier_type', 'product_category', 'city', 'province', 'region', 'pincode', 'lead_time_days', 'reliability_score', 'import_duty_rate', 'china_tax_id']

============================================================
payments
============================================================
Shape: (19257, 5)
Columns
['payment_id', 'invoice_id', 'payment_date', 'payment_amount', 'payment_method']

============================================================
stock_ledger
============================================================
Shape: (237230, 9)
Columns
['movement_id', 'product_id', 'branch_id', 'movement_type', 'movement_date', 'quantity', 'reference_type', 'reference_id', 'running_balance']

============================================================
products
============================================================
Shape: (30, 23)
Columns
['product_id', 'product_name', 'category', 'machine_type', 'brand', 'model_compatibility', 'unit_cost', 'unit_price', 'margin_percentage', 'gst_rate', 'weight_kg', 'dimensions_cm', 'material_type', 'warranty_months', 'reorder_level', 'safety_stock', 'max_stock_level', 'lead_time_days', 'criticality_level', 'usage_frequency', 'uom', 'last_purchase_price', 'last_purchase_date']

============================================================
invoices
============================================================
Shape: (18033, 10)
Columns
['invoice_id', 'so_id', 'customer_id', 'branch_id', 'invoice_date', 'due_date', 'total_order_value', 'total_gst_amount', 'grand_total', 'payment_status']

============================================================
sales_orders_header
============================================================
Shape: (20000, 11)
Columns
['so_id', 'customer_id', 'branch_id', 'order_date', 'delivery_date', 'order_status', 'payment_terms', 'total_order_value', 'total_gst_amount', 'grand_total', 'sales_channel']

In [ ]:
#check datatypes
for name, df in datasets.items():
  print('\n' + '=' * 60)
  print(f'{name}')
  print('=' * 60)
  print(df.dtypes)

============================================================
purchase_orders_lines
============================================================
po_id                object
line_number           int64
product_id           object
quantity              int64
unit_cost           float64
gst_rate              int64
line_total          float64
gst_amount          float64
line_grand_total    float64
dtype: object

============================================================
customers
============================================================
customer_id             object
customer_type           object
industry_segment        object
city                    object
state                   object
pincode                  int64
region                  object
branch_id               object
credit_limit             int64
current_balance          int64
payment_terms           object
customer_since          object
last_purchase_date      object
total_purchase_value     int64
customer_rating          int64
dtype: object

============================================================
purchase_orders_header
============================================================
po_id                      object
supplier_id                object
branch_id                  object
order_date                 object
expected_delivery_date     object
received_date              object
po_status                  object
total_cost                float64
total_gst_amount          float64
grand_total               float64
dtype: object

============================================================
sales_orders_lines
============================================================
so_id                object
line_number           int64
product_id           object
quantity              int64
unit_price            int64
gst_rate              int64
line_total            int64
gst_amount          float64
line_grand_total    float64
dtype: object

============================================================
inventory_master
============================================================
product_id       object
branch_id        object
opening_stock     int64
reorder_level     int64
safety_stock      int64
max_stock         int64
current_stock     int64
warehouse_bin    object
dtype: object

============================================================
branches
============================================================
branch_id                   object
branch_name                 object
city                        object
state                       object
region                      object
warehouse_type              object
warehouse_capacity          object
service_center_available    object
manager_id                   int64
total_employees              int64
avg_monthly_revenue          int64
monthly_operational_cost     int64
market_demand_index          int64
dtype: object

============================================================
suppliers
============================================================
supplier_id          object
supplier_name        object
supplier_type        object
product_category     object
city                 object
province             object
region               object
pincode               int64
lead_time_days        int64
reliability_score     int64
import_duty_rate      int64
china_tax_id         object
dtype: object

============================================================
payments
============================================================
payment_id         object
invoice_id         object
payment_date       object
payment_amount    float64
payment_method     object
dtype: object

============================================================
stock_ledger
============================================================
movement_id        object
product_id         object
branch_id          object
movement_type      object
movement_date      object
quantity            int64
reference_type     object
reference_id       object
running_balance     int64
dtype: object

============================================================
products
============================================================
product_id              object
product_name            object
category                object
machine_type            object
brand                   object
model_compatibility     object
unit_cost                int64
unit_price               int64
margin_percentage      float64
gst_rate                 int64
weight_kg              float64
dimensions_cm           object
material_type           object
warranty_months          int64
reorder_level            int64
safety_stock             int64
max_stock_level          int64
lead_time_days           int64
criticality_level       object
usage_frequency         object
uom                     object
last_purchase_price      int64
last_purchase_date      object
dtype: object

============================================================
invoices
============================================================
invoice_id            object
so_id                 object
customer_id           object
branch_id             object
invoice_date          object
due_date              object
total_order_value      int64
total_gst_amount     float64
grand_total          float64
payment_status        object
dtype: object

============================================================
sales_orders_header
============================================================
so_id                 object
customer_id           object
branch_id             object
order_date            object
delivery_date         object
order_status          object
payment_terms         object
total_order_value      int64
total_gst_amount     float64
grand_total          float64
sales_channel         object
dtype: object

In [ ]:
#check missing values
missing_summary=[]

for name, df in datasets.items():
  for column in df.columns:
    missing=df[column].isnull().sum()
    if missing>0:
      missing_summary.append({
          'Datasets': name,
          'Column': column,
          'Missing_Values': missing,
          'Missing %': round(missing / len(df) *100, 2 )
      })
missing_summary=pd.DataFrame(missing_summary)
missing_summary

                 Datasets         Column  Missing_Values  Missing %
0  purchase_orders_header  received_date            2370       9.88

In [ ]:
#duplicate summary

duplicate_summary=[]

for name, df in datasets.items():
  duplicate_summary.append({
      'Dataset': name,
      'Duplicated Rows': df.duplicated().sum()
  })
duplicate_summary=pd.DataFrame(duplicate_summary)
duplicate_summary

                   Dataset  Duplicated Rows
0    purchase_orders_lines                0
1                customers                0
2   purchase_orders_header                0
3       sales_orders_lines                0
4         inventory_master                0
5                 branches                0
6                suppliers                0
7                 payments                0
8             stock_ledger                0
9                 products                0
10                invoices                0
11     sales_orders_header                0

In [ ]:
po_header=datasets['purchase_orders_header']
po_header.groupby('po_status')['received_date'].apply(
    lambda x: x.isnull().sum()
)

po_status
Cancelled    2370
Received        0
Name: received_date, dtype: int64

In [15]:
project_path = "/content/Heavy_Supplier_Inventory_Warehouse_Analytics"

os.makedirs(f"{project_path}/notebooks", exist_ok=True)
os.makedirs(f"{project_path}/data", exist_ok=True)
os.makedirs(f"{project_path}/outputs", exist_ok=True)


print("Project folders created!")

Project folders created!

In [16]:
!find /content/Heavy_Supplier_Inventory_Warehouse_Analytics maxdepth 2 -type d

/content/Heavy_Supplier_Inventory_Warehouse_Analytics
/content/Heavy_Supplier_Inventory_Warehouse_Analytics/notebooks
/content/Heavy_Supplier_Inventory_Warehouse_Analytics/data
/content/Heavy_Supplier_Inventory_Warehouse_Analytics/outputs
find: ‘maxdepth’: No such file or directory
find: ‘2’: No such file or directory

In [17]:
for file in os.listdir('/content'):
  if file.endswith('.ipynb'):
    print(file)

01_data_profiling.ipynb

In [18]:
import shutil
notebook_name='01_data_profiling.ipynb'
shutil.copy(
    f'/content/{notebook_name}',
    f'/content/Heavy_Supplier_Inventory_Warehouse_Analytics/notebooks/{notebook_name}'
)
print('Notebook copied successfully')

Notebook copied successfully

In [19]:
print(os.listdir(
    '/content/Heavy_Supplier_Inventory_Warehouse_Analytics/notebooks'
))

['01_data_profiling.ipynb']

In [20]:

PROJECT_PATH = "/content/Heavy_Supplier_Inventory_Warehouse_Analytics"

for root, dirs, files in os.walk(PROJECT_PATH):
    print(root)
    for file in files:
        print("  ", file)

/content/Heavy_Supplier_Inventory_Warehouse_Analytics
/content/Heavy_Supplier_Inventory_Warehouse_Analytics/notebooks
   01_data_profiling.ipynb
/content/Heavy_Supplier_Inventory_Warehouse_Analytics/data
/content/Heavy_Supplier_Inventory_Warehouse_Analytics/outputs

In [ ]:
PROJECT_PATH = "/content/Heavy_Supplier_Inventory_Warehouse_Analytics"

requirements = """pandas
numpy
matplotlib
seaborn
scikit-learn
jupyter
openpyxl
"""

with open(f"{PROJECT_PATH}/requirements.txt", "w") as f:
    f.write(requirements)

print("requirements.txt created successfully!")

requirements.txt created successfully!

In [ ]:
print(os.listdir(PROJECT_PATH))

['requirements.txt', 'data', 'notebooks', 'outputs']

In [ ]:
#delete .ipynb_checkpoints
checkpoint_folder = f"{PROJECT_PATH}/.ipynb_checkpoints"

if os.path.exists(checkpoint_folder):
    shutil.rmtree(checkpoint_folder)
    print(".ipynb_checkpoints removed")
else:
    print("Checkpoint folder not found")

In [ ]:
#rename
os.rename(
    f"{PROJECT_PATH}/gitignore",
    f"{PROJECT_PATH}/.gitignore"
)

print("Renamed gitignore to .gitignore")

In [ ]:
print(os.listdir(PROJECT_PATH))

**Primary Key and Foreign Key Validation**

In [21]:
key_candidates = {
    "suppliers": "supplier_id",
    "branches": "branch_id",
    "customers": "customer_id",
    "products": "product_id",
    "inventory_master": "inventory_id",
    "purchase_orders_header": "po_id",
    "purchase_orders_lines": "po_line_id",
    "sales_orders_header": "so_id",
    "sales_orders_lines": "so_line_id",
    "invoices": "invoice_id",
    "payments": "payment_id"
}
for dataset, column, in key_candidates.items():
  df=datasets[dataset]
  print(f'\n{dataset}')
  print(f'column: {column}')
  print(f'Unique values: {df[column].nunique()}')
  print(f'Total Rows:{len(df)}')
  print(f'Duplicate IDs:{df[column].duplicated().sum()}')

suppliers
column: supplier_id
Unique values: 8
Total Rows:8
Duplicate IDs:0

branches
column: branch_id
Unique values: 6
Total Rows:6
Duplicate IDs:0

customers
column: customer_id
Unique values: 500
Total Rows:500
Duplicate IDs:0

products
column: product_id
Unique values: 30
Total Rows:30
Duplicate IDs:0

inventory_master
column: inventory_id

KeyError: 'inventory_id'

In [ ]:
print(datasets['inventory_master'].columns.tolist())

In [ ]:
#validate inventory_master
inventory=datasets['inventory_master']

print('Total Rows:', len(inventory))
print('Unique product_ids:', inventory['product_id'].nunique())
print('Unique branch_ids:', inventory['branch_id'].nunique())

# Check whether product + branch combination is unique
duplicate_combination=inventory.duplicated(
    subset=['product_id', 'branch_id']
).sum()

print('duplicated product + branch combinations:', duplicate_combination)

In [ ]:
remaining_keys = {
    "purchase_orders_header": "po_id",
    "purchase_orders_lines": "po_line_id",
    "sales_orders_header": "so_id",
    "sales_orders_lines": "so_line_id",
    "invoices": "invoice_id",
    "payments": "payment_id"
}

for dataset, column in remaining_keys.items():
    df = datasets[dataset]

    print(f"\n{dataset}")
    print(f"Column: {column}")
    print(f"Unique values: {df[column].nunique()}")
    print(f"Total rows: {len(df)}")
    print(f"Duplicate IDs: {df[column].duplicated().sum()}")

In [ ]:
print(datasets['purchase_orders_lines'].columns.tolist())

In [ ]:
print(datasets['sales_orders_lines'].columns.tolist())

In [ ]:
print(datasets['invoices'].columns.tolist())

In [ ]:
#purchase order lines

po_lines=datasets['purchase_orders_lines']
print('purchase_orders_lines:')
print('Total Rows:', len(po_lines))
print('Duplicated[ po_id + line_numeber]:', po_lines.duplicated(subset=['po_id', 'line_number']).sum())

#sales orders lines

so_lines=datasets['sales_orders_lines']
print('\nsales_orders_line:')
print('Total Rows:', len(so_lines))
print('Duplicate[so_id + line_numer]:', so_lines.duplicated(subset=['so_id', 'line_number']).sum())

In [ ]:
remaining_k = {
    "purchase_orders_header": "po_id",
    "sales_orders_header": "so_id",
    "invoices": "invoice_id",
    "payments": "payment_id"
}
for dataset, column in remaining_k.items():
  df=datasets[dataset]
  print(f'\n{dataset}')
  print(f'Columns:{column}')
  print(f'Unique Values:{df[column].nunique()}')
  print(f'Total Rows:{len(df)}')
  print(f'Duplicated IDs:{df[column].duplicated().sum()}')

In [ ]:
#investigate duplicate invoice IDs

invoices=datasets['invoices']
duplicated_invoice=invoices[invoices['invoice_id'].duplicated(keep=False)].sort_values('invoice_id')

print('Duplicated invoice rows:',len('duplicated_invoice'))
display(duplicated_invoice.head(20))

In [ ]:
#investidate duplicate payment ids
payment=datasets['payments']
duplicated_payments=payment[payment['payment_id'].duplicated(keep=False)].sort_values('payment_id')
print('Duplicated payment rows:', len(duplicated_payments))
display(duplicated_payments.head(20))

invoice id and payment id are not unique so we are not considered them as primary keys in this dataset becasue they are repeating

In [ ]:
#check invoice uniqueness

invoices=datasets['invoices']

print('Duplicated invoice_id + so_id:', invoices.duplicated(
    subset=['invoice_id', 'so_id']
).sum()
)

In [ ]:
#check payment uniqueness

payment=datasets['payments']
print('Duplicated payment_id + invoice_id:', payment.duplicated(
    subset=['payment_id', 'invoice_id']
).sum()
)

We will not remove the repeated invoice_id or payment_id values.

They aren't exact duplicate records. The IDs repeat, but the combinations are unique

**Foreign Key Validation**

In [ ]:
#purchase orders -- suppliers

po_header=datasets['purchase_orders_header']
suppliers=datasets['suppliers']

missing_suppliers=~po_header['supplier_id'].isin(suppliers['supplier_id'])
print('Pos with invalid suppliers id:', missing_suppliers.sum())

In [ ]:
#purchase orders -- branches

branches=datasets['branches']
missing_braches=~po_header['branch_id'].isin(branches['branch_id'])

print('Pos with invalid branch ids:', missing_braches.sum())

In [ ]:
#purchase order lines -- purchase order header

po_lines=datasets['purchase_orders_lines']
missing_po=~po_header['po_id'].isin(po_lines['po_id'])

print('Pos with invalid po_id:', missing_po.sum())

In [ ]:
#purchase order lines -- products
products=datasets['products']
missing_products=~po_lines['product_id'].isin(products['product_id'])

print('Pos with invalid product_ids:', missing_products.sum())

In [ ]:
#validate the sales side
#sales order -- customers
so_header=datasets['sales_orders_header']
customers=datasets['customers']

missing_customers=~so_header['customer_id'].isin(
    so_header['customer_id']
)
print('Soh with invalid customer_id:', missing_customers.sum())

In [ ]:
#sales orders -- branches
missing_branches=~so_header['branch_id'].isin(so_header['branch_id'])
print('Soh with invalid branches:', missing_branches.sum())

In [ ]:
#sales order lines -- sales order header

missing_so=~so_lines['so_id'].isin(so_header['so_id'])
print('Sales order lines with invalid so_ids:', missing_so.sum())

In [ ]:
#sales order lines -- products
missing_products=~so_lines['product_id'].isin(products['product_id'])
print('Sales order lines with invalid product_id:', missing_products.sum())

In [ ]:
#validate invoices

#invoices -- sales order
invoices=datasets['invoices']
missing_so=~invoices['so_id'].isin(so_header['so_id'])
print('Invoices with invalid so_id:', missing_so.sum())

In [ ]:
#invoice -- customer

missing_customers=~invoices['customer_id'].isin(customers['customer_id'])
print('Invoices with invalid customer_id:', missing_customers.sum())

In [ ]:
#invoice -- branch
missing_braches=~invoices['branch_id'].isin(branches['branch_id'])
print('Invoices with invalid branch_id:', missing_braches.sum())

In [ ]:
#validate payment
#payment -- invoices

payments=datasets['payments']
missing_invoices=~payments['invoice_id'].isin(invoices['invoice_id'])
print('Payments with invalid invoice_id:', missing_invoices.sum())

In [ ]:
#inventory -- products

inventory=datasets['inventory_master']
missing_products=~inventory['product_id'].isin(products['product_id'])
print('Inventory with invalid product_id:', missing_products.sum())

In [ ]:
#inventory -- branches

missing_braches=~inventory['branch_id'].isin(branches['branch_id'])
print('Inventory with invalid branch_id:', missing_braches.sum())

# Data Cleaning And Quality Improve

In [ ]:
#check datatypes

for name, df in datasets.items():
  print('\n' + '=' *60)
  print(name)
  print('=' *60)
  print(df.dtypes)

In [ ]:
#convert date columns to datetime

date_columns={
    'customers':[
        'customer_since',
        'last_purchase_date'
    ],
    'purchase_orders_header':[
        'order_date',
        'expected_delivery_date',
        'received_date'
    ],
    'payments':[
        'payment_date'
    ],
    'stock_ledger':[
        'movement_date'
    ],
    'products':[
        'last_purchase_date'
    ],
    'invoices':[
        'invoice_date',
        'due_date'
    ],
    'sales_orders_header':[
        'order_date',
        'delivery_date'
    ]
}
for dataset_name, columns in date_columns.items():
  for column in columns:
    datasets[dataset_name][column]=pd.to_datetime(datasets[dataset_name][column], errors='coerce')
print('Date conversion completed')

In [ ]:
for datasets_name, columns in date_columns.items():
  print('\n' + '='*50)
  print(datasets_name)
  print('=' *50)
  for column in columns:
    print(column, '=', datasets[datasets_name][column].dtype)

In [ ]:
#checks for invalid dates

In [ ]:
#check sales order for invalid dates
so_header=datasets['sales_orders_header']

invalid_delivery_dates=(
    so_header['delivery_date'] < so_header['order_date']
)
print('Orders with delivery date before order date:', invalid_delivery_dates.sum())

In [ ]:
#check purchase orders for invalid dates

po_header=datasets['purchase_orders_header']

invalid_expected_dates=(
    po_header['expected_delivery_date'] < po_header['order_date']
)
invalid_received_dates=(
    po_header['received_date'] < po_header['order_date']
)
print('POS with expected delivery dates before order date:', invalid_expected_dates.sum())
print('POS with received date before order date:', invalid_received_dates.sum())

In [ ]:
#check invoices for invalid dates

invoices=datasets['invoices']
invalid_due_dates=(
    invoices['due_date'] < invoices['invoice_date']
)
print('Invoices with due dates before invoice date:', invalid_due_dates.sum())

In [ ]:
#check numeric values

In [ ]:
#check quantity columns for negative values
print('purchase_order_quatities < 0:',( datasets['purchase_orders_lines']['quantity']<0 ).sum())

print('sales_orders_quantities < 0:',( datasets['sales_orders_lines']['quantity']<0).sum())

print('stock_ledger_quantities < 0:', (datasets['stock_ledger']['quantity']<0).sum())

In [ ]:
#check prices and costs

print('Negative purchase unit costs:',(datasets['purchase_orders_lines']['unit_cost']<0).sum())

print('Negatice sales unit price:', (datasets['sales_orders_lines']['unit_price']<0).sum())

print('Negative product unit price:', (datasets['products']['unit_price']<0).sum())

In [ ]:
#check inventory values

inventory=datasets['inventory_master']

print('Negative opening stock:', (datasets['inventory_master']['opening_stock']<0).sum())

print('Negative reorder level:', (datasets['inventory_master']['reorder_level']<0).sum())

print('Negative safety stock:', (datasets['inventory_master']['safety_stock']<0).sum())

print('Negative max stock:', (datasets['inventory_master']['max_stock']<0).sum())

print('Negative current stock:', (datasets['inventory_master']['current_stock']<0).sum())

In [ ]:
#check financial values

print('Negative customer credit limits:',
      (datasets["customers"]["credit_limit"] < 0).sum())

print('Negative customer balances:',
      (datasets["customers"]["current_balance"] < 0).sum())

print('Negative payment amounts:',
      (datasets["payments"]["payment_amount"] < 0).sum())

In [22]:
#check categorical/text consistency

categorical_checks = {
    "purchase_orders_header": ["po_status"],
    "sales_orders_header": ["order_status", "payment_terms", "sales_channel"],
    "payments": ["payment_method"],
    "invoices": ["payment_status"],
    "stock_ledger": ["movement_type", "reference_type"],
    "products": [
        "category",
        "machine_type",
        "brand",
        "material_type",
        "criticality_level",
        "usage_frequency",
        "uom"
    ],
    "customers": [
        "customer_type",
        "industry_segment",
        "region"
    ],
    "suppliers": [
        "supplier_type",
        "product_category",
        "region"
    ],
    "branches": [
        "region",
        "warehouse_type",
        "service_center_available"
    ]
}
for datasets_name, columns in categorical_checks.items():
  print('\n' + '='*50)
  print(datasets_name)
  print('=' *50)

  df=datasets[datasets_name]
  for column in columns:
    print(f'\n{column}:')
    print(df[column].unique())

==================================================
purchase_orders_header
==================================================

po_status:
['Received' 'Cancelled']

==================================================
sales_orders_header
==================================================

order_status:
['Delivered' 'Cancelled']

payment_terms:
['Net 30' 'Advance' 'Net 45' 'Net 15' 'Net 60']

sales_channel:
['Counter Sale' 'Dealer Network' 'Online' 'Field Sales']

==================================================
payments
==================================================

payment_method:
['Cheque' 'Credit Card' 'Bank Transfer' 'Cash' 'UPI']

==================================================
invoices
==================================================

payment_status:
['Unpaid' 'Paid' 'Partially Paid']

==================================================
stock_ledger
==================================================

movement_type:
['OUT' 'IN' 'ADJUSTMENT']

reference_type:
['SO' 'PO' 'ADJ']

==================================================
products
==================================================

category:
['Hydraulic' 'Filters' 'Undercarriage' 'Engine' 'Electrical' 'Attachments'
 'Brakes' 'Seals' 'Transmission' 'Cooling' 'Belts' 'Pins & Bushes' 'Cabin'
 'Lubricants' 'Sensors']

machine_type:
['Excavator' 'Loader' 'Bulldozer' 'Crane' 'Dumper' 'All']

brand:
['CAT' 'JCB' 'Komatsu' 'Volvo' 'Tata Hitachi' 'Generic']

material_type:
['steel' 'paper' 'synthetic' 'alloy' 'rubber' 'composite' 'cast iron'
 'copper' 'glass' 'plastic']

criticality_level:
['High' 'Medium' 'Low']

usage_frequency:
['Medium' 'High' 'Low']

uom:
['piece' 'set' 'cartridge']

==================================================
customers
==================================================

customer_type:
['Retail' 'Fleet Owner' 'Government' 'Dealer' 'Corporate']

industry_segment:
['Construction' 'Manufacturing' 'Logistics' 'Rental' 'Infrastructure'
 'Mining']

region:
['East' 'South' 'West' 'North' 'Central' 'North East']

==================================================
suppliers
==================================================

supplier_type:
['OEM' 'Local Vendor' 'Distributor']

product_category:
['Medium Parts' 'Small Parts' 'Large Parts']

region:
['South China' 'East China' 'North China']

==================================================
branches
==================================================

region:
['North' 'West' 'South' 'East']

warehouse_type:
['Central' 'Regional' 'Branch' 'Service Hub']

service_center_available:
['Yes' 'No']

In [24]:
#check business rule

inventory=datasets['inventory_master']
print('Safety stock greater than reorder stock:', (inventory['safety_stock'] > inventory['reorder_level']).sum())

print('Reorder level grater than max stock:', (inventory['reorder_level'] > inventory['max_stock']).sum())

Safety stock greater than reorder stock: 0
Reorder level grater than max stock: 0

In [25]:
products=datasets['products']

print('Product safety stock > reorder level:', (products['safety_stock'] > products['reorder_level']).sum())

print('Product reorder level > max stock:', (products['reorder_level'] > products['max_stock_level']).sum())

Product safety stock > reorder level: 0
Product reorder level > max stock: 0

In [26]:
#create cleaning log

# Create Data Cleaning Log

cleaning_log = pd.DataFrame([
    {
        "Dataset": "purchase_orders_header",
        "Column": "received_date",
        "Issue": "Missing values",
        "Finding": "2,370 missing values, all associated with Cancelled POs",
        "Action": "Retained as NULL/NaT because cancelled POs were not received"
    },
    {
        "Dataset": "Multiple datasets",
        "Column": "Date columns",
        "Issue": "Stored as object/string",
        "Finding": "Date columns were not in datetime format",
        "Action": "Converted to datetime64[ns]"
    },
    {
        "Dataset": "All datasets",
        "Column": "All columns",
        "Issue": "Duplicate rows",
        "Finding": "No exact duplicate rows found",
        "Action": "No action required"
    },
    {
        "Dataset": "All related datasets",
        "Column": "Foreign keys",
        "Issue": "Invalid references",
        "Finding": "No invalid foreign-key references found",
        "Action": "No action required"
    },
    {
        "Dataset": "sales_orders_header",
        "Column": "order_date / delivery_date",
        "Issue": "Date consistency",
        "Finding": "No delivery dates before order dates",
        "Action": "No action required"
    },
    {
        "Dataset": "purchase_orders_header",
        "Column": "order_date / expected_delivery_date / received_date",
        "Issue": "Date consistency",
        "Finding": "No invalid date sequences found",
        "Action": "No action required"
    },
    {
        "Dataset": "invoices",
        "Column": "invoice_date / due_date",
        "Issue": "Date consistency",
        "Finding": "No due dates before invoice dates",
        "Action": "No action required"
    },
    {
        "Dataset": "Multiple datasets",
        "Column": "Numeric columns",
        "Issue": "Negative values",
        "Finding": "No invalid negative quantities, prices, costs, stock, or payment amounts",
        "Action": "No action required"
    },
    {
        "Dataset": "Multiple datasets",
        "Column": "Categorical columns",
        "Issue": "Inconsistent categories",
        "Finding": "No obvious duplicate/inconsistent category labels found",
        "Action": "No standardization required"
    },
    {
        "Dataset": "inventory_master / products",
        "Column": "Stock levels",
        "Issue": "Business-rule validation",
        "Finding": "No violations of safety stock <= reorder level <= max stock",
        "Action": "No action required"
    }
])

cleaning_log

,Dataset,Column,Issue,Finding,Action
0,purchase_orders_header,received_date,Missing values,"2,370 missing values, all associated with Canc...",Retained as NULL/NaT because cancelled POs wer...
1,Multiple datasets,Date columns,Stored as object/string,Date columns were not in datetime format,Converted to datetime64[ns]
2,All datasets,All columns,Duplicate rows,No exact duplicate rows found,No action required
3,All related datasets,Foreign keys,Invalid references,No invalid foreign-key references found,No action required
4,sales_orders_header,order_date / delivery_date,Date consistency,No delivery dates before order dates,No action required
5,purchase_orders_header,order_date / expected_delivery_date / received...,Date consistency,No invalid date sequences found,No action required
6,invoices,invoice_date / due_date,Date consistency,No due dates before invoice dates,No action required
7,Multiple datasets,Numeric columns,Negative values,"No invalid negative quantities, prices, costs,...",No action required
8,Multiple datasets,Categorical columns,Inconsistent categories,No obvious duplicate/inconsistent category lab...,No standardization required
9,inventory_master / products,Stock levels,Business-rule validation,No violations of safety stock <= reorder level...,No action required

In [27]:
cleaning_log.to_csv(
    "/content/Heavy_Supplier_Inventory_Warehouse_Analytics/outputs/data_cleaning_log.csv",
    index=False
)

print("Cleaning log saved successfully.")

Cleaning log saved successfully.